create table
  public.store_info (
    id bigint generated by default as identity not null,
    potion_capacity bigint null,
    liquid_capacity bigint null,
    created_at timestamp with time zone not null default now(),
    constraint store_info_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.liquid_inventory (
    id bigint generated by default as identity not null,
    sku text null,
    name text null,
    created_at timestamp with time zone not null default now(),
    potion_type smallint[] null,
    constraint liquid_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    sku text null,
    name text null,
    price bigint null,
    created_at timestamp with time zone not null default now(),
    potion_type smallint[] null,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customer (
    id bigint generated by default as identity not null,
    name text null,
    level bigint null,
    class text null,
    created_at timestamp with time zone not null default now(),
    constraint customer_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customer_visit (
    id bigint generated by default as identity not null,
    customer_id bigint null,
    timestamp text null,
    created_at timestamp with time zone not null default now(),
    visit_id bigint null default '-1'::bigint,
    constraint customer_visit_pkey primary key (id),
    constraint customer_visit_customer_id_fkey foreign key (customer_id) references customer (id)
  ) tablespace pg_default;

  create table
  public.cart (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    customer_id bigint null,
    payment_method text null,
    constraint cart_pkey primary key (id),
    constraint cart_customer_id_fkey foreign key (customer_id) references customer (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id integer null,
    potion_id integer null,
    quantity integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references cart (id),
    constraint cart_items_inventory_id_fkey foreign key (potion_id) references potion_inventory (id)
  ) tablespace pg_default;

  create view
  public.audit as
  select
    (
      select
        sum(gold_ledger_entries.change) as sum
      from
        gold_ledger_entries
    ) as gold,
    (
      select
        sum(potion_ledger_entries.change) as sum
      from
        potion_ledger_entries
    ) as number_of_potions,
    (
      select
        sum(liquid_ledger_entries.change) as sum
      from
        liquid_ledger_entries
    ) as ml_in_barrels;

    create view
  public.cart_checkout as
select
  cart_items.cart_id,
  cart_items.quantity as cart_item_quantity,
  potion_stock.id as potion_id,
  potion_stock.potion_type,
  potion_stock.price as potion_price,
  potion_stock.quantity as potion_inventory_quantity
from
  cart
  join cart_items on cart.id = cart_items.cart_id
  join potion_stock on cart_items.potion_id = potion_stock.id;

  create table
  public.gold_ledger_entries (
    id bigint generated by default as identity not null,
    gold_transaction_id bigint null,
    change double precision null,
    created_at timestamp with time zone not null default now(),
    constraint gold_ledger_entries_pkey primary key (id),
    constraint gold_ledger_entries_gold_transaction_id_fkey foreign key (gold_transaction_id) references gold_transactions (id)
  ) tablespace pg_default;

  create table
  public.gold_transactions (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    description text null,
    cart_id bigint null,
    constraint gold_transactions_pkey primary key (id),
    constraint gold_transactions_cart_id_fkey foreign key (cart_id) references cart (id)
  ) tablespace pg_default;

  create table
  public.liquid_ledger_entries (
    id bigint generated by default as identity not null,
    liquid_transactions_id bigint null,
    liquid_id bigint null,
    change bigint null,
    created_at timestamp with time zone not null default now(),
    constraint liquid_ledger_entries_pkey primary key (id),
    constraint liquid_ledger_entries_liquid_id_fkey foreign key (liquid_id) references liquid_inventory (id),
    constraint liquid_ledger_entries_liquid_transactions_id_fkey foreign key (liquid_transactions_id) references liquid_transactions (id)
  ) tablespace pg_default;

  create view
  public.liquid_stock as
select
  li.id,
  li.sku,
  li.potion_type,
  sum(lle.change) as quantity
from
  liquid_inventory li
  join liquid_ledger_entries lle on li.id = lle.liquid_id
group by
  li.id,
  li.sku,
  li.potion_type
order by
  li.id;

  create table
  public.liquid_transactions (
    id bigint generated by default as identity not null,
    description text null,
    created_at timestamp with time zone not null default now(),
    constraint liquid_transactions_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_ledger_entries (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    potion_id bigint null,
    potion_transactions_id bigint null,
    change bigint null,
    constraint potion_ledger_entries_pkey primary key (id),
    constraint potion_ledger_entries_potion_id_fkey foreign key (potion_id) references potion_inventory (id),
    constraint potion_ledger_entries_potion_transactions_id_fkey foreign key (potion_transactions_id) references potion_transactions (id)
  ) tablespace pg_default;

  create view
  public.potion_stock as
select
  pi.id,
  pi.sku,
  pi.name,
  pi.potion_type,
  pi.price,
  sum(ple.change) as quantity
from
  potion_inventory pi
  join potion_ledger_entries ple on pi.id = ple.potion_id
group by
  pi.id,
  pi.sku,
  pi.potion_type,
  pi.price;

  create table
  public.potion_transactions (
    id bigint generated by default as identity not null,
    description text null,
    created_at timestamp with time zone not null default now(),
    constraint potion_transactions_pkey primary key (id)
  ) tablespace pg_default;

  create view
  public.store_data as
select
  (
    select
      sum(gold_ledger_entries.change) as sum
    from
      gold_ledger_entries
  ) as gold,
  (
    select
      sum(potion_ledger_entries.change) as sum
    from
      potion_ledger_entries
  ) as number_of_potions,
  (
    select
      sum(liquid_ledger_entries.change) as sum
    from
      liquid_ledger_entries
  ) as ml_in_barrels,
  (
    select
      store_info.potion_capacity
    from
      store_info
    limit
      1
  ) as potion_capacity,
  (
    select
      store_info.liquid_capacity
    from
      store_info
    limit
      1
  ) as liquid_capacity;