create table
  public.store_info (
    id bigint generated by default as identity not null,
    gold bigint null,
    potion_capacity bigint null,
    liquid_capacity bigint null,
    created_at timestamp with time zone not null default now(),
    constraint store_info_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.liquid_inventory (
    id bigint generated by default as identity not null,
    sku text null,
    name text null,
    quantity bigint null,
    created_at timestamp with time zone not null default now(),
    potion_type smallint[] null,
    constraint liquid_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    sku text null,
    name text null,
    price bigint null,
    quantity bigint null,
    created_at timestamp with time zone not null default now(),
    potion_type smallint[] null,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customer (
    id bigint generated by default as identity not null,
    name text null,
    level bigint null,
    class text null,
    created_at timestamp with time zone not null default now(),
    constraint customer_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customer_visit (
    id bigint generated by default as identity not null,
    customer_id bigint null,
    timestamp text null,
    created_at timestamp with time zone not null default now(),
    visit_id bigint null default '-1'::bigint,
    constraint customer_visit_pkey primary key (id),
    constraint customer_visit_customer_id_fkey foreign key (customer_id) references customer (id)
  ) tablespace pg_default;

  create table
  public.cart (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    customer_id bigint null,
    payment_method text null,
    constraint cart_pkey primary key (id),
    constraint cart_customer_id_fkey foreign key (customer_id) references customer (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id integer null,
    potion_id integer null,
    quantity integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references cart (id),
    constraint cart_items_inventory_id_fkey foreign key (potion_id) references potion_inventory (id)
  ) tablespace pg_default;